### ISSUE TITLE
请问这些包可以编译到哪个版本的Openwrt？

### ISSUE THREAD

**Issue by kuoruan** [openwrt-stuff/openwrt-maz1#1]
Chaos Calmer还是BarrierBreaker？
我主要想编译 luci-app-macvlan，是直接放进去就可以了么？

**Comment by wongsyrone** [comment]
CC

**Comment by kuoruan** [comment]
哇，大神，你这么多小号么？我准备试试官方的，看看官方的正常不，路由器经常死机我都不知道怎么办

**Comment by wongsyrone** [comment]
这两个包我看maz貌似并没有做什么改动，估计你的问题还会出现

**Comment by kuoruan** [comment]
主要是我不会改luci，如果会的话，就不会这么累了

**Comment by wongsyrone** [comment]
macvlan这个我记得是官方维护的，你可以报bug到官方packages仓库，当然要用英语描述

**Comment by kuoruan** [comment]
macvlan没问题，虚拟端口都正常，就是mwan3有问题，但是问题不大。现在最大的问题是路由老死机，影响使用了

**Comment by wongsyrone** [comment]
@kuoruan 
你那个死机的问题看看flash和ram吧，不行换一片

**Comment by kuoruan** [comment]
不好意思，我问个问题啊，官方CC加这个包里边的luci-app-macvlan和mwan3，编译出来后不能用，是不是有补丁需要打？

**Comment by kuoruan** [comment]
现在行了，我先把pppd的patch打上了，然后发现我包的文件权限有问题，把文件的执行权限加上了就正常了，但是不知道是pppd这个补丁是干什么的？

**Comment by maz-1** [comment]
这个补丁是并发拨号用的

**Comment by kuoruan** [comment]
已经搞定，感谢！
