### ISSUE TITLE
luci-app-ngrokc使用TCP方式有Bug

### ISSUE THREAD

**Issue by kuoruan** [openwrt-stuff/openwrt-maz1#4]
一直提示 `一个或多个必选项值为空！`

**Comment by maz-1** [comment]
好久没折腾openwrt了，等买了新路由再看看

**Comment by maz-1** [comment]
https://github.com/openwrt-stuff/openwrt-extra/tree/master/luci/applications/luci-ngrokc

**Comment by kuoruan** [comment]
这个 issue 老久了额，经过这几个月的学习，我也会写 luci 了。。
